language: node_js
node_js:
  - "8"
  - "10"
install:
  - npm install
script:
  - npm run lint
  - npm run build
deploy:
  provider: pages
  local-dir: api-docs
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
